apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-role
subjects:
  - name: flux-source-controller
    namespace: flux-system 
    kind: ServiceAccount               
